apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexical-clash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lexical-clash
  template:
    metadata:
      labels:
        app: lexical-clash
    spec:
      containers:
        - name: lexical-clash
          image: ghcr.io/jml-89/lexical-clash:73dda35b7b65f4b979768944872d609b6f1a24c7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: lexical-clash-vars
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"

