apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexical-clash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lexical-clash
  template:
    metadata:
      labels:
        app: lexical-clash
    spec:
      containers:
        - name: lexical-clash
          image: ghcr.io/jml-89/lexical-clash@sha256:54fed368a82c5c8802367e22d54c2661bb3110177ade25b6b413ee3ebca06bd8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: lexical-clash-vars
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"

