apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexical-clash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lexical-clash
  template:
    metadata:
      labels:
        app: lexical-clash
    spec:
      containers:
        - name: lexical-clash
          image: ghcr.io/jml-89/lexical-clash@sha256:bc4e4f5c0d8f5928a793db8b319fc25b110be6c318304353c134a4171fdfc07a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: lexical-clash-vars
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"

