name: Test Kustomize
on: 
  push:
    branches:
      - 'main'

jobs:
  kustomize:
    name: Kustomize
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: kustomize ./
